[package]
name = "krnlstring"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/rthidfrev/krnlstring/"
authors = ["rthidfrev"]



[dependencies.windows-sys]
version = "0.59.0"
features = ["Win32_Foundation"]
